<a href="https://colab.research.google.com/github/harita-gr/AI_ML_Practice/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Integer Array

In [ ]:
integers = np.array([10,20,30,40,50])
print(integers)

[10 20 30 40 50]


Try to insert a float value to integer array.

O/P: The values gets chopped/rounded to integer

In [ ]:
integers[0] = 34.2
integers

array([34, 20, 30, 40, 50])

Find Array Type

In [ ]:
integers.dtype

dtype('int64')

Enforce Array Type

In [ ]:
smallerIntegers = np.array(integers, dtype=np.int8)
smallerIntegers

array([34, 20, 30, 40, 50], dtype=int8)

See Difference in Type

In [ ]:
integers.nbytes

5

In [ ]:
smallerIntegers.nbytes

5

## Multi Dimensional Array


In [ ]:
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
nums[0,0]

1

In [ ]:
nums[1,4]

10

Find dimensions of an array

In [ ]:
nums.ndim

2

## Creating Array from Python Structures

List

In [ ]:
first_list=[1,2,3,4,5] #integers
first_array=np.array(first_list)
first_array

array([1, 2, 3, 4, 5])

In [ ]:
second_list=[1,2,4,-1.24,56,1280000.56] #integers, float
second_array=np.array(second_list)
second_array

array([ 1.00000000e+00,  2.00000000e+00,  4.00000000e+00, -1.24000000e+00,
        5.60000000e+01,  1.28000056e+06])

In [ ]:
third_list=[1,2,"Ann", 13232, "John"] #integers, string
third_array=np.array(third_list)
third_array

array(['1', '2', 'Ann', '13232', 'John'], dtype='<U21')

Tuple

In [ ]:
first_tuple=(5,10,18,30)
array_from_tuple = np.array(first_tuple)
array_from_tuple

array([ 5, 10, 18, 30])

In [ ]:
array_from_tuple.dtype

dtype('int64')

## Intrinsic NumPy array creation

Integer Array - `arange`

In [ ]:
integers_array = np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
integers_second_array = np.arange(100,130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [ ]:
integers_third_array = np.arange(100,130,2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128])

Float Array - `linspace`

In [ ]:
first_floats_arr = np.linspace(10,20)
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [ ]:
second_floats_arr = np.linspace(10,20,5)
second_floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

Creating Array with Random Values

In [ ]:
first_rand_arr = np.random.rand(10)
first_rand_arr

array([0.51865824, 0.25817935, 0.98808966, 0.01964566, 0.923881  ,
       0.36918335, 0.34179153, 0.81481092, 0.13752853, 0.39775235])

In [ ]:
second_rand_arr = np.random.rand(4,4)
second_rand_arr

array([[0.1535405 , 0.73182279, 0.88654039, 0.51316989],
       [0.46665161, 0.82831274, 0.24527574, 0.2235644 ],
       [0.14764597, 0.20777631, 0.6096765 , 0.26945275],
       [0.44614355, 0.21707782, 0.46530431, 0.75449318]])

In [ ]:
third_rand_arr = np.random.randint(0,100,20)
third_rand_arr

array([82, 47, 88,  1, 66, 17, 12, 92, 85, 40, 34, 74, 20, 94, 70, 55,  8,
       80, 33, 51])

Creating arrays filled with constant values

In [ ]:
first_z_arr = np.zeros(5) # 1-d array
first_z_arr

array([0., 0., 0., 0., 0.])

In [ ]:
second_z_arr = np.zeros((4,5)) # tuple for 2-d array
second_z_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
first_ones_arr = np.ones(6)
first_ones_arr

array([1., 1., 1., 1., 1., 1.])

In [ ]:
second_ones_arr = np.ones((4,5)) # tuple for 2-d array
second_ones_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

`fill` - 1D array
`full` - 1D and 2D array

In [ ]:
first_fill_arr = np.empty(10,dtype=int) #create empty array first
first_fill_arr.fill(12)
first_fill_arr

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [ ]:
first_full_arr = np.full(5,10)
first_full_arr

array([10, 10, 10, 10, 10])

In [ ]:
sec_full_arr = np.full((4,5),10)
sec_full_arr

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

## Finding the shape and size of an array

In [ ]:
first_arr = np.arange(20)
second_arr = np.linspace((1,2),(10,20),10)
third_arr = np.full((2,2,2),10)

In [ ]:
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.shape(first_arr)

(20,)

In [ ]:
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [ ]:
np.shape(second_arr)

(10, 2)

In [ ]:
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [ ]:
np.shape(third_arr)

(2, 2, 2)

In [ ]:
np.size(first_arr)

20

In [ ]:
np.size(second_arr)

20

In [ ]:
np.size(third_arr)

8

## Manipulate NumPy Arrays

Adding, Removing, Sorting

In [ ]:
first_arr = np.array([1,2,3])
first_arr

array([1, 2, 3])

In [ ]:
np.insert(first_arr,3,4) # insert didn't do anything to original array
first_arr

array([1, 2, 3])

In [ ]:
new_arr = np.insert(first_arr,3,4) # add element at an index
new_arr

array([1, 2, 3, 4])

In [ ]:
sec_arr = np.append(new_arr,7)
sec_arr

array([1, 2, 3, 4, 7])

In [ ]:
del_arr = np.delete(sec_arr,3)
del_arr

array([1, 2, 3, 7])

In [ ]:
integers_arr = np.random.randint(0,20,20)
integers_arr

array([19,  1,  8,  4, 13, 12,  1,  0, 19,  6, 11, 18,  5, 19,  9,  3, 10,
        5, 11, 14])

In [ ]:
print(np.sort(integers_arr))

[ 0  1  1  3  4  5  5  6  8  9 10 11 11 12 13 14 18 19 19 19]


In [ ]:
integers_2d_arr = np.array([[3,5,1],[4,6,1]])
integers_2d_arr

array([[3, 5, 1],
       [4, 6, 1]])

In [ ]:
print(np.sort(integers_2d_arr))

[[1 3 5]
 [1 4 6]]


In [ ]:
colors = np.array(["orange","red","green","pink"])
print(np.sort(colors))

['green' 'orange' 'pink' 'red']


Copies & Views

In [ ]:
students_id_number = np.array([111,122,344,135,161,172])
students_id_number_reg = students_id_number

print("id of students_id_number",id(students_id_number))
print("id of students_id_number_reg",id(students_id_number_reg))

#same ids

id of students_id_number 138620461167312
id of students_id_number_reg 138620461167312


In [ ]:
students_id_number_reg[2] = 333

print("id of students_id_number",students_id_number)
print("id of students_id_number_reg",students_id_number_reg)

# changes reflected in both array. so they are the same

id of students_id_number [111 122 333 135 161 172]
id of students_id_number_reg [111 122 333 135 161 172]


Copy


In [ ]:
students_id_number_cp = students_id_number.copy()
print(students_id_number_cp)

[111 122 333 135 161 172]


In [ ]:
print(students_id_number_cp == students_id_number )

[ True  True  True  True  True  True]


In [ ]:
print("id of students_id_number",id(students_id_number))
print("id of students_id_number_cp",id(students_id_number_cp))

id of students_id_number 138620461167312
id of students_id_number_cp 138620461163472


In [ ]:
students_id_number[0] = 100 # change made to org array

print("org:",students_id_number)
print("copy:",students_id_number_cp)

# copy is not affected. both are diff

org: [100 122 333 135 161 172]
copy: [111 122 333 135 161 172]


View

In [ ]:
students_id_number_view = students_id_number.view()
students_id_number[0] = 2000

print("org:",students_id_number)
print("view:",students_id_number_view)

# change in org affects view

org: [2000  122  333  135  161  172]
view: [2000  122  333  135  161  172]


Base

In [ ]:
print("org:",students_id_number.base)
print("view:",students_id_number_view.base)

org: None
view: [2000  122  333  135  161  172]


Reshape

In [ ]:
first_arr = np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
sec_arr = np.reshape(first_arr,(3,4))
sec_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
sec_arr = np.reshape(first_arr,(6,2))
sec_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
third_arr = np.reshape(first_arr,(4,4)) #incompatible shape
third_arr

# throws error

ValueError: cannot reshape array of size 12 into shape (4,4)

In [ ]:
fourth_arr = np.reshape(first_arr,(3,2,2))
print(fourth_arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
sixth_arr_flat = np.reshape(fourth_arr, -1) # convert to 1D
sixth_arr_flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Joining and splitting arrays

In [ ]:
first_arr = np.arange(1,11)
sec_arr = np.arange(11,21)

con_arr = np.concatenate((first_arr,sec_arr)) # join two 1D arrays
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
first_arr = np.array([[1,4,6],[11,2,3]])
sec_arr = np.array([[4,14,6],[11,25,32]])

con_arr = np.concatenate((first_arr,sec_arr), axis=1) # join two 2-D arrays
con_arr

array([[ 1,  4,  6,  4, 14,  6],
       [11,  2,  3, 11, 25, 32]])

In [ ]:
fifth_arr = np.arange(1,13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
sp_arr = np.array_split(fifth_arr,4)
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

## Arithmetic operations and functions

In [ ]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [ ]:
a-b

array([-20, -20, -20, -20, -20, -20, -20, -20, -20, -20])

In [ ]:
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [ ]:
b/a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [ ]:
a**b

array([                  1,             4194304,         94143178827,
           281474976710656,  298023223876953125, 4561031516192243712,
       5059972980857283351,                   0, 5756027422282277481,
       5076944270305263616])

## Aggregate Functions

In [ ]:
np.average(a)

5.5

In [ ]:
np.std(b)

2.8722813232690143

## Get unique items and counts

In [ ]:
a = np.array([1,4,3,1,4,5])
np.unique(a)

array([1, 3, 4, 5])

Returns tuple of 2 arrays

In [ ]:
np.unique(a, return_index=True) # 2nd array contains index positions of first array

(array([1, 3, 4, 5]), array([0, 2, 1, 5]))

To find frequency of each element

In [ ]:
np.unique(a, return_counts=True) # 2nd array contains freq of first array

(array([1, 3, 4, 5]), array([2, 1, 2, 1]))